AUTH_ROUTE = "auth"
STUDENT_ROUTE = "students"
PARENT_ROUTE = "parents"
TEACHER_ROUTE = "teachers"
QUESTION_ROUTE = "questions"
CHECK_ROUTE = "check"
TEST_ROUTE = "test"
CLASS_ROUTE = "class"

__all__ = ["AUTH_ROUTE", "STUDENT_ROUTE", "PARENT_ROUTE", "TEACHER_ROUTE", "QUESTION_ROUTE", "CHECK_ROUTE", "TEST_ROUTE", "CLASS_ROUTE"]
